# Generated by Django 5.1.1 on 2025-09-30 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kezdoEv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Het',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hetfoDatum', models.DateField()),
                ('bevetel', models.IntegerField(default=0)),
                ('diakok', models.ManyToManyField(blank=True, related_name='hetek', to=settings.AUTH_USER_MODEL)),
                ('tanev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hetek', to='app_repont.tanev')),
            ],
        ),
    ]
