# Generated by Django 5.1.1 on 2025-09-30 20:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kobanya150_Idoszak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kezdoDatum', models.DateField()),
                ('vegDatum', models.DateField()),
            ],
            options={
                'verbose_name': 'Időszak',
                'verbose_name_plural': 'Időszakok',
                'ordering': ['-kezdoDatum'],
            },
        ),
        migrations.CreateModel(
            name='kobanya150_Alkalom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datum', models.DateField()),
                ('ido_kezdes', models.TimeField(default=datetime.time(0, 0))),
                ('ido_vege', models.TimeField(default=datetime.time(0, 0))),
                ('max_letszam', models.IntegerField(blank=True, null=True)),
                ('jelentkezok', models.ManyToManyField(blank=True, related_name='kobanya150_alkalmak', to=settings.AUTH_USER_MODEL)),
                ('idoszak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alkalmak', to='app_kobanya150.kobanya150_idoszak')),
            ],
            options={
                'verbose_name': 'Alkalom',
                'verbose_name_plural': 'Alkalmak',
                'ordering': ['-datum'],
            },
        ),
    ]
