# Generated by Django 5.1.1 on 2025-09-30 18:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kobanya150', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kobanya150_alkalom',
            name='ido_kezdes',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='kobanya150_alkalom',
            name='ido_vege',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='kobanya150_alkalom',
            name='idoszak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alkalmak', to='app_kobanya150.kobanya150_idoszak'),
        ),
    ]
