# Generated by Django 5.1.1 on 2025-09-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kobanya150', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobanya150_alkalom',
            name='max_letszam',
            field=models.IntegerField(default=-1),
        ),
    ]
