# Generated by Django 5.1.1 on 2025-09-26 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kobanya150', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='kobanya150_Alkalom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('jelentkezok', models.ManyToManyField(blank=True, related_name='kobanya150_alkalmak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='kobanya150_Idoszak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kezdoDatum', models.DateField()),
                ('vegDatum', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='het',
            name='diakok',
        ),
        migrations.RemoveField(
            model_name='het',
            name='tanev',
        ),
        migrations.DeleteModel(
            name='Tanev',
        ),
        migrations.AddField(
            model_name='kobanya150_alkalom',
            name='idoszak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alkalomok', to='app_kobanya150.kobanya150_idoszak'),
        ),
        migrations.DeleteModel(
            name='Het',
        ),
    ]
