# Generated by Django 5.1.1 on 2025-09-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kobanya150', '0002_kobanya150_alkalom_kobanya150_idoszak_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kobanya150_alkalom',
            options={'ordering': ['-datum'], 'verbose_name': 'Alkalom', 'verbose_name_plural': 'Alkalmak'},
        ),
        migrations.AlterModelOptions(
            name='kobanya150_idoszak',
            options={'ordering': ['-kezdoDatum'], 'verbose_name': 'Időszak', 'verbose_name_plural': 'Időszakok'},
        ),
    ]
