# Generated by Django 5.1.1 on 2025-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kobanya150', '0002_kobanya150_alkalom_ido_kezdes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobanya150_alkalom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
