# Generated by Django 5.1.1 on 2025-09-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kobanya150', '0003_alter_kobanya150_alkalom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kobanya150_idoszak',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
